# Generated by Django 4.1.6 on 2023-02-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='observacao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
