# Generated by Django 4.1.6 on 2023-02-08 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0003_paciente_prontuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico', verbose_name='Nome do Médico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente', verbose_name='Nome do Paciente'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome_medico',
            field=models.CharField(max_length=50, verbose_name='Nome do Médico'),
        ),
    ]
